ProFivea/ProFivea/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from appFive import views

urlpatterns = [
    path('',views.index, name = 'index_h'),
    path('admin/', admin.site.urls),
    path('appFive/',include('appFive.urls')),
    path('logout/',views.user_logout,name = 'logout_h'),
    path('special/',views.special, name = 'special_h'),
]

ProFivea/appFive/urls.py
from django.urls import path
from appFive import views

app_name = 'appFivea'

urlpatterns = [
    path('register/',views.register, name = 'register_h'),
    path('user_login/', views.user_login, name = 'user_login_h')
]

ProFivea/appFive/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    portfolio_site = models.URLField(blank = True )
    profile_pic = models.ImageField(upload_to = 'profile_pics_folder', blank = True )

    def __str__(self):
        return self.user.username

ProFivea/appFive/forms.py
from django import forms
from django.contrib.auth.models import User
from appFive.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

ProFivea/appFive/views.py
from django.shortcuts import render
from appFive.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'appFive/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in Nice!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'appFive/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index_h'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print('Someone tried to login but failed')
            print('Username: {}, password {}'.format(username,password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request, 'appFive/login.html',{})

ProFivea/templates/appFive/appFive.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
          <a class = 'navbar-brand' href="{% url 'index_h' %}">Django </a>
          <a class = 'nav-item nav-link' href="{% url 'admin:index' %}">Admin </a>
          <a class = 'nav-item nav-link' href="{% url 'appFivea:register_h' %}">Register</a>

          {% if user.is_authenticated %}
          <a class = 'nav-item nav-link' href="{% url 'logout_h' %}">Logout</a>

          {% else %}
          <a class = 'nav-item nav-link' href="{% url 'appFivea:user_login_h' %}"> Login</a>

          {% endif %}
        </div>
      </nav>
    </div>


    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

ProFivea/templates/appFive/index.html
<!DOCTYPE html>


{% extends 'appFive/appFive.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1> Thankyou for registering</h1>
  {% else %}
    <h1> Register here </h1>
    <h3> Fill out the form</h3>
    <form class="" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" method = "POST" name="" value="Register">
    </form>
  {% endif %}

</div>

{% endblock %}

ProFivea/templates/appFive/login.html
<!DOCTYPE html>
{% extends 'appFive/appFive.html' %}


{% block body_block %}
<div class="jumbotron">
  <h1>Please login</h1>

  <form  action="{% url 'appFivea:user_login_h' %}" method="post">
    {% csrf_token %}
    <label for="username"> Username: </label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password"> Password: </label>
    <input type="password" name="password" >
    <input type="submit" name="" value="Login">
  </form>

</div>
{% endblock %}

ProFivea/templates/appFive/register.html
{% extends "appFive/appFive.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}